---

common:
  k8s_namespace: ingress-nginx

  app_name: nginx-ingress
  replicas_count: 2
  image_version: 0.23.0

  network_policy_ingress: {}
  network_policy_egress: {}

  templates:
    - template: 000_namespace.yaml.j2
    - template: 001_serviceAccount.yaml.j2
    - template: 002_service.yaml.j2
    - template: 003_networkPolicy.yaml.j2
    - template: 010_clusterRole.yaml.j2
    - template: 011_role.yaml.j2
    - template: 012_roleBinding.yaml.j2
    - template: 013_clusterRoleBinging.yaml.j2
    - template: 020_configmapNginxConfiguration.yaml.j2
    - template: 021_configmapTCPServices.yaml.j2
    - template: 022_configmapUDPServices.yaml.j2
    - template: 030_deployment.yaml.j2

public:
  app_name: external-ingress
  network_policy_egress:
    selectors:
      - namespaceSelector: "name: public"
        podSelector: "app: back1" # Через публичный ingress можно получить доступ только к определённому приложению
      - namespaceSelector: "name: kube-system"
        podSelector: "k8s-app: kube-dns" # Доступ к местному DNS серверу, для резолва доменов

secure:
  app_name: kube-ingress
  network_policy_ingress:
    cidrs: # Доступ к роутеру можно получить только с определённых сетей(произвольный выбор, просто для примера)
      - 10.100.0.0/16
      - 10.123.0.0/16
