---

common:

  app_name: nginx-ingress
  app_namespace: ingress-nginx

  replicas_count: 1

  image_version: 0.23.0

  templates:
    - template: 000_namespace.yaml
    - template: 001_serviceAccount.yaml
    - template: 002_service.yaml
    - template: 010_clusterRole.yaml
    - template: 011_role.yaml
    - template: 012_roleBinding.yaml
    - template: 013_clusterRoleBinging.yaml
    - template: 020_configmapNginxConfiguration.yaml
    - template: 021_configmapTCPServices.yaml
    - template: 022_configmapUDPServices.yaml
    - template: 030_deployment.yaml

public:
  app_name: nginx-ingress-public

secure:
  app_name: nginx-ingress-secure
