---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ app_name }}-serviceaccount
  namespace: {{ app_namespace }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/part-of: {{ app_name }}
