---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ app_name }}
  namespace: {{ k8s_namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ app_name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  {% if network_policy_ingress_cidr -%}
    - from:
      - ipBlock:
          cidr: {{ network_policy_ingress_cidr }}
  {% else -%}
    - {} # allow all ingress traffic
  {% endif -%}
  egress:
  {% if network_policy_egress_cidr -%}
    - to:
      - ipBlock:
          cidr: {{ network_policy_egress_cidr }}
  {% else -%}
    - {} # allow all egress traffic
  {% endif -%}
