---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ app_name }}-role-nisa-binding
  namespace: {{ app_namespace }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/part-of: {{ app_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ app_name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ app_name }}-serviceaccount
    namespace: {{ app_namespace }}
